# Generated by Django 2.2.4 on 2019-09-01 07:14

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammodel',
            name='question',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='aa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exammodel',
            name='score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scoremodel',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
