# Generated by Django 2.2.4 on 2019-09-01 08:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20190901_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoremodel',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='aaaaa'),
            preserve_default=False,
        ),
    ]
