# Generated by Django 2.2.4 on 2019-08-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_videomodel_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='source',
            field=models.FileField(upload_to='E:\\Python\\mooc_site\\media/'),
        ),
    ]
