# Generated by Django 2.2.4 on 2019-08-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20190829_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='sorting',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
