# Generated by Django 2.2.4 on 2019-09-03 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('video', '0006_auto_20190831_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.SelectionModel')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.VideoModel')),
            ],
        ),
    ]
